service: oneupwebapp

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment:
    ONEUP_DEMOWEBAPPLOCAL_CLIENTSECRET: ${env:ONEUP_DEMOWEBAPPLOCAL_CLIENTSECRET}
    ONEUP_DEMOWEBAPPLOCAL_CLIENTID: ${env:ONEUP_DEMOWEBAPPLOCAL_CLIENTID}
    NODE_ENV: production
    NEXT_ASSET_PREFIX: dev

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}