version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:12.3.1-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linter
          command: "echo 'TODO: add linter command'"
      - run:
          name: Run tests
          command: "echo 'TODO: add test command'"
      - run:
          name: Build
          command: npm run build
  deploy:
    parallelism: 1
    shell: /bin/bash --login
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: "AWS_ACCESS_KEY_ID"
          aws-secret-access-key: "AWS_SECRET_ACCESS_KEY"
          aws-region: "AWS_DEFAULT_REGION"
      - run: npm run deploy:staging
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #  branches:
          #    only: master