version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:12.3.1-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linter
          command: "echo 'TODO: add linter command'"
      - run:
          name: Run tests
          command: "echo 'TODO: add test command'"
      - run:
          name: Build
          command: npm run build
  deploy:
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:12.3.1-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run: npm run deploy:dev
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #  branches:
          #    only: master